import { Listing } from '../definitions/listing.types';

export const listingsData: Listing[] = [
  {
    id: '1',
    title: 'Golden Beach Field A',
    slug: 'golden-beach-field-a',
    address: {
      streetNumber: '123',
      streetName: 'Main St',
      city: 'New York',
      state: 'NY',
      zipCode: '10001',
      country: 'USA',
      coordinates: {
        lat: 40.7128,
        lng: -74.006,
      },
    },
    listingType: 'buy',
    category: 'residential',
    propertyType: 'house',
    price: 100000,
    bedrooms: 3,
    bathrooms: 2,
    squareMeters: 100,
    features: ['air conditioning', 'heating', 'fireplace'],
    furnishing: 'furnished',
    amenities: ['swimming pool', 'gym', 'jacuzzi'],
    suitableFor: ['family', 'couple', 'single'],
    view: ['sea', 'mountain', 'city'],
    publishedAt: new Date(),
    updatedAt: new Date(),
    isFeatured: true,
    isActive: true,
    tags: ['tag1', 'tag2', 'tag3'],
    images: [
      '/golden-beach-field-A/golden_beach_field_A_1.JPG',
      '/golden-beach-field-A/golden_beach_field_A_2.JPG',
      '/golden-beach-field-A/golden_beach_field_A_3.JPG',
      '/golden-beach-field-A/golden_beach_field_A_4.JPG',
      '/golden-beach-field-A/golden_beach_field_A_5.JPG',
      '/golden-beach-field-A/golden_beach_field_A_6.JPG',
      '/golden-beach-field-A/golden_beach_field_A_7.JPG',
      '/golden-beach-field-A/golden_beach_field_A_8.JPG',
      '/golden-beach-field-A/golden_beach_field_A_9.JPG',
      '/golden-beach-field-A/golden_beach_field_A_10.JPG',
    ],
    description: 'Description 1',
  },
  {
    id: '1',
    title: 'Golden Beach Field A',
    slug: 'golden-beach-field-a',
    address: {
      streetNumber: '123',
      streetName: 'Main St',
      city: 'New York',
      state: 'NY',
      zipCode: '10001',
      country: 'USA',
      coordinates: {
        lat: 40.7128,
        lng: -74.006,
      },
    },
    listingType: 'buy',
    category: 'residential',
    propertyType: 'house',
    price: 100000,
    bedrooms: 3,
    bathrooms: 2,
    squareMeters: 100,
    features: ['air conditioning', 'heating', 'fireplace'],
    furnishing: 'furnished',
    amenities: ['swimming pool', 'gym', 'jacuzzi'],
    suitableFor: ['family', 'couple', 'single'],
    view: ['sea', 'mountain', 'city'],
    publishedAt: new Date(),
    updatedAt: new Date(),
    isFeatured: true,
    isActive: true,
    tags: ['tag1', 'tag2', 'tag3'],
    images: [
      '/golden-beach-field-A/golden_beach_field_A_1.JPG',
      '/golden-beach-field-A/golden_beach_field_A_2.JPG',
      '/golden-beach-field-A/golden_beach_field_A_3.JPG',
      '/golden-beach-field-A/golden_beach_field_A_4.JPG',
      '/golden-beach-field-A/golden_beach_field_A_5.JPG',
      '/golden-beach-field-A/golden_beach_field_A_6.JPG',
      '/golden-beach-field-A/golden_beach_field_A_7.JPG',
      '/golden-beach-field-A/golden_beach_field_A_8.JPG',
      '/golden-beach-field-A/golden_beach_field_A_9.JPG',
      '/golden-beach-field-A/golden_beach_field_A_10.JPG',
    ],
    description: 'Description 1',
  },
];
