import { Listing } from '../definitions/listing.types';

const gb = (n: number) => ({
  url: `images/leonettis/golden-beach-field-1/golden_beach_field_A_${n}.webp`,
  name: `Golden Beach Field ${n}`,
  description: '',
});

const py = (n: number, fileNum: number) => ({
  url: `images/leonettis/pyrgaki-field-2/pyrgaki-field-2-${fileNum}.webp`,
  name: `Pyrgaki Field ${n}`,
  description: '',
});

const mm = (n: number) => ({
  url: `images/leonettis/marpissa-marios/marpissa-marios-${n}.jpg`,
  name: `Marpissa Marios ${n}`,
  description: '',
});

const mH3 = (n: number) => ({
  url: `images/leonettis/marpissa-house-3/marpissa-house-3-${n}.webp`,
  name: `Marpissa House 3 ${n}`,
  description: '',
});

const pireas2 = (n: number) => ({
  url: `images/leonettis/pireas-2/pireas-2-${n}.webp`,
  name: `Pireas 2 ${n}`,
  description: '',
});

export const listingsData: Listing[] = [
  {
    id: 'mock-1',
    title: {
      en: 'Golden Beach Plot',
      fr: 'Parcelle à Golden Beach',
      gr: 'Οικόπεδο στην Χρυσή Ακτή',
      de: 'Goldener Strand Plot',
      it: 'Plot di Golden Beach',
    },
    slug: 'golden-beach-plot',
    address: {
      streetNumber: '',
      streetName: 'Golden Beach',
      city: '',
      state: 'Πάρος',
      zipCode: '84001',
      country: 'GR',
      coordinates: {
        lat: 36.4074,
        lng: 25.363,
      },
    },
    listingType: 'buy',
    category: ['residential'],
    propertyType: 'field',
    price: 100000,
    bedrooms: 0,
    bathrooms: 0,
    squareMetersTotal: 100,
    features: [],
    furnishing: 'furnished',
    amenities: [],
    suitableFor: ['family', 'couple', 'single'],
    view: ['sea', 'mountain'],
    publishedAt: '',
    updatedAt: '',
    isFeatured: true,
    isActive: true,
    tags: ['tag1', 'tag2', 'tag3'],
    availableUponRequest: true,
    images: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10].map((n) => gb(n)),
    description: {
      en: 'Description 1',
      fr: 'Description 1',
      gr: 'Description 1',
      de: 'Description 1',
      it: 'Description 1',
    },
  },
  {
    id: 'mock-2',
    title: {
      en: 'Plot in Pyrgaki',
      fr: 'Parcelle à Pyrgaki',
      gr: 'Οικόπεδο στο Πυργάκι',
      de: 'Plot in Pyrgaki',
      it: 'Plot in Pyrgaki',
    },
    slug: 'plot-in-pyrgaki',
    address: {
      streetNumber: '123',
      streetName: 'Pyrgaki',
      city: 'Πύργακι',
      state: 'Πάρος',
      zipCode: '84005',
      country: 'GR',
      coordinates: {
        lat: 36.4074,
        lng: 25.363,
      },
    },
    listingType: 'buy',
    category: ['residential'],
    propertyType: 'land',
    price: 100000,
    bedrooms: 0,
    bathrooms: 0,
    squareMetersTotal: 100,
    features: [],
    furnishing: 'furnished',
    amenities: [],
    suitableFor: ['family', 'couple', 'single'],
    view: ['sea', 'mountain'],
    publishedAt: '',
    updatedAt: '',
    isFeatured: true,
    isActive: true,
    tags: ['tag1', 'tag2', 'tag3'],
    images: [
      py(1, 1),
      py(2, 2),
      py(3, 3),
      py(4, 4),
      py(5, 5),
      py(6, 6),
      py(7, 7),
      py(8, 8),
      py(9, 10),
      py(10, 11),
      py(11, 12),
      py(12, 13),
      py(13, 14),
      py(14, 15),
    ],
    videos: [
      {
        url: 'images/leonettis/pyrgaki-field-2/pyrgaki-field-2-9.mp4',
        name: 'pyrgaki-field-2-9.mp4',
      },
    ],
    description: {
      en: 'Description 1',
      fr: 'Description 1',
      gr: 'Description 1',
      de: 'Description 1',
      it: 'Description 1',
    },
  },
  {
    id: 'real-3', // Unknown
    title: {
      en: 'Two-Bedroom House with Roof Garden in Marpissa',
      fr: 'Maison de deux chambres avec jardin sur le toit à Marpissa',
      gr: 'Σπίτι δύο υπνοδωματίων με roof garden στη Μάρπησσα',
      de: 'Haus mit zwei Schlafzimmern und Dachgarten in Marpissa',
      it: 'Casa con due camere da letto e giardino pensile a Marpissa',
    },
    description: {
      en: 'A two-bedroom house featuring King Size beds, a home gym, and a rooftop garden. The layout includes a kitchen and living room on the first floor, with two bedrooms and a large bathroom upstairs. There is also an additional WC on the lower level.',
      fr: "Une maison de deux chambres comprenant des lits King Size, une salle de sport à domicile et un jardin sur le toit. La disposition comprend une cuisine et un salon au premier étage, avec deux chambres et une grande salle de bain à l'étage. Il y a également un WC supplémentaire au niveau inférieur.",
      gr: 'Σπίτι δύο υπνοδωματίων στη Μάρπησσα με κρεβάτια King Size, γυμναστήριο και roof garden. Διαθέτει κουζίνα και σαλόνι στον πρώτο όροφο, δύο υπνοδωμάτια με μεγάλο μπάνιο στον επάνω όροφο και WC στο κάτω επίπεδο.',
      de: 'Ein Haus mit zwei Schlafzimmern, King-Size-Betten, einem Fitnessraum und einem Dachgarten. Die Aufteilung umfasst eine Küche und ein Wohnzimmer im ersten Stock, zwei Schlafzimmer und ein großes Badezimmer im Obergeschoss. Außerdem gibt es ein zusätzliches WC auf der unteren Ebene.',
      it: 'Una casa con due camere da letto dotata di letti King Size, una palestra privata e un giardino sul tetto. La disposizione comprende cucina e soggiorno al primo piano, con due camere da letto e un ampio bagno al piano superiore. È presente anche un ulteriore WC al piano inferiore.',
    },
    slug: 'house-marpissa-paros-rent',
    address: {
      streetNumber: '',
      streetName: '',
      city: 'Marpissa',
      state: 'South Aegean',
      region: 'Paros',
      zipCode: '',
      country: 'Greece',
      coordinates: {
        lat: 0, // Unknown
        lng: 0, // Unknown
      },
      displayAddress: 'Marpissa, Paros, Greece',
    },
    listingType: 'rent',
    category: ['residential'],
    propertyType: 'house',
    bedrooms: 2,
    bathrooms: 2, // Mentioned a large bathroom upstairs and a WC downstairs
    squareMetersInterior: 0, // Unknown
    squareMetersOutdoor: 0, // Unknown
    squareMetersTotal: 0, // Unknown
    images: Array.from({ length: 31 }, (_, i) => mm(i + 1)),
    mainImage: '',
    videos: [],
    features: [
      'terrace', // Roof garden/terrace mentioned
    ],
    furnishing: 'furnished', // Implied by mention of specific bed sizes and gym equipment
    amenities: ['gym', 'terrace'],
    suitableFor: [
      'vacation home', // Mentioned Airbnb as an alternative
    ],
    view: [],
    publishedAt: '2026-02-22T14:08:55Z',
    updatedAt: '2026-02-22T14:08:55Z',
    isFeatured: false,
    isActive: true,
    isSold: false,
    isRented: false,
    tags: ['Marpissa', 'Paros', 'Roof Garden', 'Gym'],
    favorite: false,
    urgent: false,
    condition: 'renovated',
    yearBuilt: 0, // Unknown
    energyRating: 'A', // Schema placeholder
    availableNow: false,
    availableUponRequest: true,
  },
  {
    id: 'mock-4',
    title: {
      en: 'Off-Market Estate, Paros',
      fr: 'Propriété hors marché, Paros',
      gr: 'Εκτός αγοράς ακίνητο, Πάρος',
      de: 'Off-Market Immobilie, Paros',
      it: 'Proprietà fuori mercato, Paros',
    },
    slug: 'off-market-paros-estate',
    address: {
      streetNumber: '',
      streetName: '',
      city: 'Paros',
      state: 'South Aegean',
      region: 'Cyclades',
      zipCode: '84400',
      country: 'GR',
      coordinates: {
        lat: 37.0853,
        lng: 25.1489,
      },
      displayAddress: 'Paros, Cyclades, Greece',
    },
    listingType: 'buy',
    category: ['residential'],
    propertyType: 'house',
    bedrooms: 5,
    bathrooms: 4,
    squareMetersTotal: 420,
    features: ['terrace', 'garden'],
    furnishing: 'furnished',
    amenities: ['swimming pool'],
    suitableFor: ['family'],
    view: ['sea'],
    publishedAt: '2026-04-01T12:00:00Z',
    updatedAt: '2026-04-01T12:00:00Z',
    isFeatured: false,
    isActive: true,
    tags: ['off-market', 'luxury'],
    images: [gb(1), gb(2)],
    description: {
      en: 'Luxury off-market property; price available on request.',
      fr: 'Propriété de luxe hors marché ; prix sur demande.',
      gr: 'Πολυτελές εκτός αγοράς· η τιμή κατόπιν αιτήματος.',
      de: 'Luxuriöse Off-Market-Immobilie; Preis auf Anfrage.',
      it: 'Proprietà di lusso fuori mercato; prezzo su richiesta.',
    },
  },
  {
    id: 'real-5',
    title: {
      en: 'Two-Floor Building for Renovation in Marpissa Square, Paros',
      gr: 'Διώροφο κτίριο προς ανακαίνιση στην πλατεία Μάρπησσας, Πάρος',
      fr: 'Bâtiment à deux étages à rénover sur la place de Marpissa, Paros',
      de: 'Zweistöckiges Renovierungsgebäude am Platz von Marpissa, Paros',
      it: 'Edificio a due piani da ristrutturare in piazza Marpissa, Paros',
    },
    description: {
      en: 'A rare opportunity: a two-floor building located directly on the square (platia) of Marpissa, Paros. The property requires full renovation and offers exceptional versatility - it can be used as a residential home or converted into a commercial space such as a shop or restaurant (food service / hygionomiko). The plot measures 154.13 m², is buildable within settlement limits, and is 1,280 m from the sea.',
      gr: 'Σπάνια ευκαιρία: διώροφο κτίριο στην πλατεία Μάρπησσας, Πάρου. Χρειάζεται ανακαίνιση και προσφέρει εξαιρετική ευελιξία - κατοικία ή μετατροπή σε κατάστημα / χώρο εστίασης (υγειονομικού ενδιαφέροντος). Το οικόπεδο έχει εμβαδόν 154,13 τ.μ., βρίσκεται εντός ορίων οικισμού, 1.280 μ. από τη θάλασσα.',
      fr: 'Opportunité rare : bâtiment de deux étages situé directement sur la place (platia) de Marpissa, Paros. La propriété nécessite une rénovation complète et offre une polyvalence exceptionnelle - habitation ou conversion en espace commercial (boutique, restaurant). Le terrain mesure 154,13 m², constructible en zone de village, à 1 280 m de la mer.',
      de: 'Eine seltene Gelegenheit: zweistöckiges Gebäude direkt am Platz (Platia) von Marpissa, Paros. Vollständige Renovierung erforderlich. Außergewöhnlich vielseitig nutzbar - als Wohnhaus oder als Geschäft / Gastronomie umrüstbar. Grundstück 154,13 m², bebaubar innerhalb der Siedlungsgrenzen, 1.280 m vom Meer.',
      it: "Rara opportunità: edificio a due piani situato direttamente sulla piazza (platia) di Marpissa, Paros. L'immobile necessita di ristrutturazione completa e offre eccezionale versatilità - residenza o conversione in spazio commerciale (negozio, ristorante). Il terreno è di 154,13 m², edificabile entro i confini del villaggio, a 1.280 m dal mare.",
    },
    slug: 'marpissa-house-3',
    address: {
      streetName: '',
      streetNumber: '',
      city: 'Marpissa',
      state: 'South Aegean',
      region: 'Paros',
      zipCode: '',
      country: 'Greece',
      coordinates: { lat: 0, lng: 0 },
      displayAddress: 'Marpissa, Paros, Greece',
    },
    listingType: 'buy',
    category: ['residential', 'commercial'],
    propertyType: 'house',
    squareMetersTotal: 154,
    images: Array.from({ length: 23 }, (_, i) => mH3(i + 1)),
    mainImage: '',
    videos: [],
    features: ['terrace', 'garden'],
    amenities: [],
    suitableFor: ['investment', 'business', 'family'],
    view: [],
    condition: 'renovation needed',
    publishedAt: '2026-04-22T12:00:00Z',
    updatedAt: '2026-04-22T12:00:00Z',
    isFeatured: false,
    isActive: true,
    isSold: false,
    isRented: false,
    favorite: false,
    urgent: false,
    tags: [
      'Marpissa',
      'Paros',
      'Platia',
      'Renovation',
      'Commercial',
      'Investment',
    ],
  },
  {
    id: 'piraeus-commercial-1',
    title: {
      en: 'Commercial Space in Piraeus – Warehouse, Shop & Office',
      fr: 'Espace Commercial au Pirée – Entrepôt, Boutique & Bureau',
      gr: 'Επαγγελματικός Χώρος στον Πειραιά',
      de: 'Gewerbefläche in Piräus – Lager, Geschäft & Büro',
      it: 'Spazio Commerciale al Pireo – Magazzino, Negozio & Ufficio',
    },
    description: {
      en: 'A 300sqm commercial space in Piraeus comprising a 125sqm ground floor, 40sqm mezzanine, and 135sqm basement. Suitable for use as a warehouse, shop, or office. Renovation needed. Located 500m from the metro station. No common charges.',
      fr: 'Espace commercial de 300m² au Pirée comprenant un rez-de-chaussée de 125m², une mezzanine de 40m² et un sous-sol de 135m². Convient à un usage entrepôt, boutique ou bureau. Rénovation nécessaire. Situé à 500m de la station de métro. Pas de charges communes.',
      gr: 'Επαγγελματικός χώρος 300τμ στον Πειραιά, αποτελούμενος από ισόγειο 125τμ, πατάρι 40τμ και υπόγειο 135τμ. Κατάλληλος για αποθήκη, κατάστημα ή γραφείο. Χρειάζεται ανακαίνιση. Βρίσκεται 500μ από σταθμό μετρό. Χωρίς κοινόχρηστα.',
      de: '300m² Gewerbefläche in Piräus bestehend aus 125m² Erdgeschoss, 40m² Zwischengeschoss und 135m² Untergeschoss. Geeignet als Lager, Geschäft oder Büro. Renovierung erforderlich. 500m zur nächsten U-Bahnstation. Keine Nebenkosten.',
      it: 'Spazio commerciale di 300mq al Pireo composto da piano terra 125mq, soppalco 40mq e seminterrato 135mq. Adatto ad uso magazzino, negozio o ufficio. Necessita di ristrutturazione. A 500m dalla stazione della metropolitana. Nessuna spesa condominiale.',
    },
    slug: 'commercial-space-piraeus-buy',
    address: {
      city: 'Piraeus',
      state: 'Attica',
      country: 'Greece',
      zipCode: '',
      coordinates: { lat: 37.9428, lng: 23.6466 },
      displayAddress: 'Piraeus, Attica, Greece',
    },
    listingType: 'buy',
    category: ['commercial'],
    propertyType: 'business',
    price: 210000,
    squareMetersInterior: 300,
    squareMetersTotal: 300,
    images: Array.from({ length: 8 }, (_, i) => pireas2(i + 1)),
    mainImage: '',
    condition: 'renovation needed',
    publishedAt: '2026-04-22T00:00:00Z',
    updatedAt: '2026-04-22T00:00:00Z',
    isFeatured: false,
    isActive: true,
    isSold: false,
    availableNow: true,
    tags: [
      'Piraeus',
      'Commercial',
      'Business',
      'Warehouse',
      'Shop',
      'Office',
      'Metro',
    ],
  },
];
