import { Listing } from '../definitions/listing.types';

const gb = (n: number) => ({
  url: `images/leonettis/golden-beach-field-1/golden_beach_field_A_${n}.webp`,
  name: `Golden Beach Field ${n}`,
  description: '',
});

const py = (n: number, fileNum: number) => ({
  url: `images/leonettis/pyrgaki-field-2/pyrgaki-field-2-${fileNum}.webp`,
  name: `Pyrgaki Field ${n}`,
  description: '',
});

const mm = (n: number) => ({
  url: `images/leonettis/marpissa-marios/marpissa-marios-${n}.jpg`,
  name: `Marpissa Marios ${n}`,
  description: '',
});

export const listingsData: Listing[] = [
  {
    id: '1',
    title: {
      en: 'Golden Beach Plot',
      fr: 'Parcelle à Golden Beach',
      gr: 'Οικόπεδο στην Χρυσή Ακτή',
      de: 'Goldener Strand Plot',
      it: 'Plot di Golden Beach',
    },
    slug: 'golden-beach-plot',
    address: {
      streetNumber: '',
      streetName: 'Golden Beach',
      city: '',
      state: 'Πάρος',
      zipCode: '84001',
      country: 'GR',
      coordinates: {
        lat: 36.4074,
        lng: 25.363,
      },
    },
    listingType: 'buy',
    category: 'residential',
    propertyType: 'field',
    price: 100000,
    bedrooms: 0,
    bathrooms: 0,
    squareMetersTotal: 100,
    features: [],
    furnishing: 'furnished',
    amenities: [],
    suitableFor: ['family', 'couple', 'single'],
    view: ['sea', 'mountain'],
    publishedAt: '',
    updatedAt: '',
    isFeatured: true,
    isActive: true,
    tags: ['tag1', 'tag2', 'tag3'],
    availableUponRequest: true,
    images: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10].map((n) => gb(n)),
    description: {
      en: 'Description 1',
      fr: 'Description 1',
      gr: 'Description 1',
      de: 'Description 1',
      it: 'Description 1',
    },
  },
  {
    id: '2',
    title: {
      en: 'Plot in Pyrgaki',
      fr: 'Parcelle à Pyrgaki',
      gr: 'Οικόπεδο στο Πυργάκι',
      de: 'Plot in Pyrgaki',
      it: 'Plot in Pyrgaki',
    },
    slug: 'plot-in-pyrgaki',
    address: {
      streetNumber: '123',
      streetName: 'Pyrgaki',
      city: 'Πύργακι',
      state: 'Πάρος',
      zipCode: '84005',
      country: 'GR',
      coordinates: {
        lat: 36.4074,
        lng: 25.363,
      },
    },
    listingType: 'buy',
    category: 'residential',
    propertyType: 'land',
    price: 100000,
    bedrooms: 0,
    bathrooms: 0,
    squareMetersTotal: 100,
    features: [],
    furnishing: 'furnished',
    amenities: [],
    suitableFor: ['family', 'couple', 'single'],
    view: ['sea', 'mountain'],
    publishedAt: '',
    updatedAt: '',
    isFeatured: true,
    isActive: true,
    tags: ['tag1', 'tag2', 'tag3'],
    images: [
      py(1, 1),
      py(2, 2),
      py(3, 3),
      py(4, 4),
      py(5, 5),
      py(6, 6),
      py(7, 7),
      py(8, 8),
      py(9, 10),
      py(10, 11),
      py(11, 12),
      py(12, 13),
      py(13, 14),
      py(14, 15),
    ],
    videos: ['images/leonettis/pyrgaki-field-2/pyrgaki-field-2-9.mp4'],
    description: {
      en: 'Description 1',
      fr: 'Description 1',
      gr: 'Description 1',
      de: 'Description 1',
      it: 'Description 1',
    },
  },
  {
    id: '3', // Unknown
    title: {
      en: 'Two-Bedroom House with Roof Garden in Marpissa',
      fr: 'Maison de deux chambres avec jardin sur le toit à Marpissa',
      gr: 'Σπίτι δύο υπνοδωματίων με roof garden στη Μάρπησσα',
      de: 'Haus mit zwei Schlafzimmern und Dachgarten in Marpissa',
      it: 'Casa con due camere da letto e giardino pensile a Marpissa',
    },
    description: {
      en: 'A two-bedroom house featuring King Size beds, a home gym, and a rooftop garden. The layout includes a kitchen and living room on the first floor, with two bedrooms and a large bathroom upstairs. There is also an additional WC on the lower level.',
      fr: "Une maison de deux chambres comprenant des lits King Size, une salle de sport à domicile et un jardin sur le toit. La disposition comprend une cuisine et un salon au premier étage, avec deux chambres et une grande salle de bain à l'étage. Il y a également un WC supplémentaire au niveau inférieur.",
      gr: 'Σπίτι δύο υπνοδωματίων στη Μάρπησσα με κρεβάτια King Size, γυμναστήριο και roof garden. Διαθέτει κουζίνα και σαλόνι στον πρώτο όροφο, δύο υπνοδωμάτια με μεγάλο μπάνιο στον επάνω όροφο και WC στο κάτω επίπεδο.',
      de: 'Ein Haus mit zwei Schlafzimmern, King-Size-Betten, einem Fitnessraum und einem Dachgarten. Die Aufteilung umfasst eine Küche und ein Wohnzimmer im ersten Stock, zwei Schlafzimmer und ein großes Badezimmer im Obergeschoss. Außerdem gibt es ein zusätzliches WC auf der unteren Ebene.',
      it: 'Una casa con due camere da letto dotata di letti King Size, una palestra privata e un giardino sul tetto. La disposizione comprende cucina e soggiorno al primo piano, con due camere da letto e un ampio bagno al piano superiore. È presente anche un ulteriore WC al piano inferiore.',
    },
    slug: 'house-marpissa-paros-rent',
    address: {
      streetNumber: '',
      streetName: '',
      city: 'Marpissa',
      state: 'South Aegean',
      region: 'Paros',
      zipCode: '',
      country: 'Greece',
      coordinates: {
        lat: 0, // Unknown
        lng: 0, // Unknown
      },
      displayAddress: 'Marpissa, Paros, Greece',
    },
    listingType: 'rent',
    category: 'residential',
    propertyType: 'house',
    bedrooms: 2,
    bathrooms: 2, // Mentioned a large bathroom upstairs and a WC downstairs
    squareMetersInterior: 0, // Unknown
    squareMetersOutdoor: 0, // Unknown
    squareMetersTotal: 0, // Unknown
    images: Array.from({ length: 31 }, (_, i) => mm(i + 1)),
    mainImage: '',
    videos: [],
    features: [
      'terrace', // Roof garden/terrace mentioned
    ],
    furnishing: 'furnished', // Implied by mention of specific bed sizes and gym equipment
    amenities: ['gym', 'terrace'],
    suitableFor: [
      'vacation home', // Mentioned Airbnb as an alternative
    ],
    view: [],
    publishedAt: '2026-02-22T14:08:55Z',
    updatedAt: '2026-02-22T14:08:55Z',
    isFeatured: false,
    isActive: true,
    isSold: false,
    isRented: false,
    tags: ['Marpissa', 'Paros', 'Roof Garden', 'Gym'],
    favorite: false,
    urgent: false,
    condition: 'renovated',
    yearBuilt: 0, // Unknown
    energyRating: 'A', // Schema placeholder
    availableNow: false,
    availableUponRequest: true,
  },
  {
    id: '4',
    title: {
      en: 'Off-Market Estate, Paros',
      fr: 'Propriété hors marché, Paros',
      gr: 'Εκτός αγοράς ακίνητο, Πάρος',
      de: 'Off-Market Immobilie, Paros',
      it: 'Proprietà fuori mercato, Paros',
    },
    slug: 'off-market-paros-estate',
    address: {
      streetNumber: '',
      streetName: '',
      city: 'Paros',
      state: 'South Aegean',
      region: 'Cyclades',
      zipCode: '84400',
      country: 'GR',
      coordinates: {
        lat: 37.0853,
        lng: 25.1489,
      },
      displayAddress: 'Paros, Cyclades, Greece',
    },
    listingType: 'buy',
    category: 'residential',
    propertyType: 'house',
    bedrooms: 5,
    bathrooms: 4,
    squareMetersTotal: 420,
    features: ['terrace', 'garden'],
    furnishing: 'furnished',
    amenities: ['swimming pool'],
    suitableFor: ['family'],
    view: ['sea'],
    publishedAt: '2026-04-01T12:00:00Z',
    updatedAt: '2026-04-01T12:00:00Z',
    isFeatured: false,
    isActive: true,
    tags: ['off-market', 'luxury'],
    images: [gb(1), gb(2)],
    description: {
      en: 'Luxury off-market property; price available on request.',
      fr: 'Propriété de luxe hors marché ; prix sur demande.',
      gr: 'Πολυτελές εκτός αγοράς· η τιμή κατόπιν αιτήματος.',
      de: 'Luxuriöse Off-Market-Immobilie; Preis auf Anfrage.',
      it: 'Proprietà di lusso fuori mercato; prezzo su richiesta.',
    },
  },
];
