import './globals.css';

import type { Metadata } from 'next';

import LocalizedLink from '@/app/ui/LocalizedLink';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <nav>
          <LocalizedLink href="/">Home</LocalizedLink>
          <LocalizedLink href="/about">About</LocalizedLink>
          <LocalizedLink href="/buy">Buy</LocalizedLink>
          <LocalizedLink href="/rent">Rent</LocalizedLink>
          <LocalizedLink href="/sell">Sell</LocalizedLink>
          <LocalizedLink href="/blog">Blog</LocalizedLink>
          <LocalizedLink href="/contact">Contact</LocalizedLink>
        </nav>
        <main className="antialiased">{children}</main>
        <footer>
          <p>Copyright 2026 Leonetti&apos;s</p>
        </footer>
      </body>
    </html>
  );
}
