import './globals.css';

import type { Metadata } from 'next';

//TODO: for Real Estate SEO, make sure to use rel="alternate" hreflang="..." tags in your metadata so Google knows which page is for which language.

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">{children}</body>
    </html>
  );
}
